# Repository settings for GitHub Settings app
# See: https://github.com/probot/settings

repository:
  # Repository name
  name: erldantic

  # A short description of the repository
  description: "A data validation library for Erlang inspired by Pydantic"

  # Repository homepage URL
  homepage: https://github.com/andreashasse/erldantic

  # Repository topics/tags
  topics: erlang, validation, json, pydantic, openapi, schema

  # Either `true` to make the repository private, or `false` to make it public
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them
  has_downloads: true

  # Updates the default branch for this repository
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent squash-merging
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false` to prevent merge commits
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent rebase-merging
  allow_rebase_merge: true

  # Either `true` to enable automatic deletion of head branches when pull requests are merged, or `false` to disable
  delete_branch_on_merge: true

  # Either `true` to allow automatically merging pull requests, or `false` to prevent auto-merge
  allow_auto_merge: true

  # Either `true` to enable the use of the update branch button, or `false` to disable
  allow_update_branch: true

# Branch protection rules
branches:
  - name: main
    protection:
      # Required. Require at least one approving review on a pull request, before merging
      required_pull_request_reviews:
        # Required. Require review from code owners
        require_code_owner_reviews: false
        # Required. Dismiss stale PR approvals when new commits are pushed
        dismiss_stale_reviews: true
        # Required. Number of required reviewers
        required_approving_review_count: 1

      # Required. Require status checks to pass before merging
      required_status_checks:
        # Required. Require branches to be up to date before merging
        strict: true
        # Required. List of required status checks
        contexts:
          - "CI"

      # Required. Enforce all configured restrictions for administrators
      enforce_admins: false

      # Required. Restrict pushes that create files larger than this limit
      restrictions: null

      # Required. Block creations
      block_creations: false