name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          rebar3-version: '3.25'

      - name: Download and Setup ELP
        run: |
          mkdir -p bin
          wget -q 'https://github.com/WhatsApp/erlang-language-platform/releases/download/2025-07-08/elp-linux-x86_64-unknown-linux-gnu-otp-27.3.tar.gz' -O elp.tar.gz
          tar -xzf elp.tar.gz
          mv elp bin/
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          echo "ELP installed at ${{ github.workspace }}/bin/elp"

      - name: Install dependencies
        run: rebar3 get-deps

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"

          # Allow Claude to run rebar3 commands during review
          allowed_tools: "Bash(make build-test),Bash(rebar3 *)"

          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this Erlang pull request focusing on:
            - Erlang/OTP best practices and conventions
            - Pattern matching and function clause efficiency
            - Proper error handling. This library should not crash, so check for potential runtime errors.
            - Module design and API clarity
            - Run `make build-test` to ensure the code compiles and passes tests.

            Be constructive and helpful in your feedback.
